module. exports = {
    MissingToken: "The token entered is invalid or not found!",
    InvalidIntent: "You must select 'Guild_Members' intents in your discord developer portal!",
    error: "An unexpected error has occurred! Please contact support for assistance.",
    disable: "Disabled",
    enable: "Enabled",
    replace: "Replaced",
    checkConfig: {
        DeveloperGuild: "You must enter your server ID.",
        AntiRaid: "Values in 'antiraid' config must equal true/false",
        Emergency: "Values in 'emergency' config must equal true/false",
        limits: "Values in config 'limits' must be an integer",
        restore: "Values in 'restore' config must equal true/false",
        sanction: "Values in config 'sanction' must equal 'Ban' / 'Kick' / 'RemoveRole'",
        warning1: "Warning! in your config you have disabled",
        warning2: "but you have activated",
    },
    channelCreate: {
        removeRole1: "All your server roles",
        removeRole2: " have been removed for security reasons (You have exceeded the limit of created anti raid channels)",
        removeRoleCatch1: "Member",
        removeRoleCatch2: "has exceeded the Anti Raid limit but I can't remove the role from it",
        Kick1: "You have been kicked from the server",
        Kick2: "for security reasons (You have exceeded the limit of anti-raid created channels)",
        KickCatch1: "The Member",
        KickCatch2: "Exceeded the Anti Raid limit but I can't kick it!",
        Ban1: "You have been banned from the server",
        Ban2: "for security reasons (You have exceeded the limit of created anti-raid channels)",
        BanCatch1: "Member",
        BanCatch2: "Exceeded the Anti Raid limit but I can't ban him!",
    },
    channelDelete: {
        removeRole1: "All your server roles",
        removeRole2: " have been removed for security reasons (You have exceeded the anti raid removed channel limit)",
        removeRoleCatch1: "Member",
        removeRoleCatch2: "has exceeded the Anti Raid limit but I can't remove the role from it",
        Kick1: "You have been kicked from the server",
        Kick2: "for security reasons (You have exceeded the anti raid deleted channels limit)",
        KickCatch1: "The Member",
        KickCatch2: "Exceeded the Anti Raid limit but I can't kick it!",
        Ban1: "You have been banned from the server",
        Ban2: "for security reasons (You have exceeded the anti raid deleted channels limit)",
        BanCatch1: "Member",
        BanCatch2: "Exceeded the Anti Raid limit but I can't ban him!",
        embed: {
            title: "Anti raid - Channel recreated",
            description: "This channel was deleted by a malicious person, so I recreated it!",
        },
    },
    emojiCreate: {
        removeRole1: "All your server roles",
        removeRole2: " have been removed for security reasons (You have exceeded the limit of anti raid created emojis)",
        removeRoleCatch1: "Member",
        removeRoleCatch2: "has exceeded the Anti Raid limit but I can't remove the role from it",
        Kick1: "You have been kicked from the server",
        Kick2: "for security reasons (You have exceeded the limit of anti raid created emojis)",
        KickCatch1: "The Member",
        KickCatch2: "Exceeded the Anti Raid limit but I can't kick it!",
        Ban1: "You have been banned from the server",
        Ban2: "for security reasons (You have exceeded the limit of anti raid created emojis)",
        BanCatch1: "Member",
        BanCatch2: "Exceeded the Anti Raid limit but I can't ban him!",
    },
    emojiDelete: {
        removeRole1: "All your server roles",
        removeRole2: " have been removed for security reasons (You have exceeded the limit of anti raid removed emojis)",
        removeRoleCatch1: "Member",
        removeRoleCatch2: "has exceeded the Anti Raid limit but I can't remove the role from it",
        Kick1: "You have been kicked from the server",
        Kick2: "for security reasons (You have exceeded the anti raid deleted emoji limit)",
        KickCatch1: "The Member",
        KickCatch2: "Exceeded the Anti Raid limit but I can't kick it!",
        Ban1: "You have been banned from the server",
        Ban2: "for security reasons (You have exceeded the limit of anti raid deleted emojis)",
        BanCatch1: "Member",
        BanCatch2: "Exceeded the Anti Raid limit but I can't ban him!",
    },
    banAdd: {
        removeRole1: "All your rolesserver's",
        removeRole2: " have been removed for security reasons (You have exceeded the limit of users banned from anti raid)",
        removeRoleCatch1: "Member",
        removeRoleCatch2: "has exceeded the Anti Raid limit but I can't remove the role from it",
        Kick1: "You have been kicked from the server",
        Kick2: "for security reasons (You have exceeded the limit of users banned from anti raid)",
        KickCatch1: "The Member",
        KickCatch2: "Exceeded the Anti Raid limit but I can't kick it!",
        Ban1: "You have been banned from the server",
        Ban2: "for security reasons (You have exceeded the limit of users banned from anti raid)",
        BanCatch1: "Member",
        BanCatch2: "Exceeded the Anti Raid limit but I can't ban him!",
    },
    banRemove: {
        removeRole1: "All your server roles",
        removeRole2: " have been removed for security reasons (You have exceeded the limit of unbanned anti raid users)",
        removeRoleCatch1: "Member",
        removeRoleCatch2: "has exceeded the Anti Raid limit but I can't remove the role from it",
        Kick1: "You have been kicked from the server",
        Kick2: "for security reasons (You have exceeded the limit of unbanned anti raid users)",
        KickCatch1: "The Member",
        KickCatch2: "Exceeded the Anti Raid limit but I can't kick it!",
        Ban1: "You have been banned from the server",
        Ban2: "for security reasons (You have exceeded the limit of unbanned anti-raid users)",
        BanCatch1: "Member",
        BanCatch2: "Exceeded the Anti Raid limit but I can't ban him!",
    },
    roleCreate: {
        removeRole1: "All your server roles",
        removeRole2: " have been removed for security reasons (You have exceeded the limit of anti raid created roles)",
        removeRoleCatch1: "Member",
        removeRoleCatch2: "has exceeded the Anti Raid limit but I can't remove the role from it",
        Kick1: "You have been kicked from the server",
        Kick2: "for security reasons (You have exceeded the limit of anti raid created roles)",
        KickCatch1: "The Member",
        KickCatch2: "Exceeded the Anti Raid limit but I can't kick it!",
        Ban1: "You have been banned from the server",
        Ban2: "for security reasons (You have exceeded the limit of created anti-raid roles)",
        BanCatch1: "Member",
        BanCatch2: "Exceeded the Anti Raid limit but I can't ban him!",
    },
    roleDelete: {
        removeRole1: "All your server roles",
        removeRole2: " have been removed for security reasons (You have exceeded the limit of anti raid removed roles)",
        removeRoleCatch1: "Member",
        removeRoleCatch2: "has exceeded the Anti Raid limit but I can't remove the role from it",
        Kick1: "You have been kicked from the server",
        Kick2: "for security reasons (You have exceeded the anti raid deleted roles limit)",
        KickCatch1: "The Member",
        KickCatch2: "Exceeded the Anti Raid limit but I can't kick it!",
        Ban1: "You have been banned from the server",
        Ban2: "for security reasons (You have exceeded the anti raid deleted roles limit)",
        BanCatch1: "Member",
        BanCatch2: "Exceeded the Anti Raid limit but I can't ban him!",
    },
    stickerCreate: {
        removeRole1: "All your server roles",
        removeRole2: " have been removed for security reasons (You have exceeded the anti raid sticker creation limit)",
        removeRoleCatch1: "Member",
        removeRoleCatch2: "has exceeded the Anti Raid limit but I can't remove the role from it",
        Kick1: "You have been kicked from the server",
        Kick2: "for security reasons (You have exceeded the anti-raid sticker creation limit)",
        KickCatch1: "The Member",
        KickCatch2: "Exceeded the Anti Raid limit but I can't kick it!",
        Ban1: "You have been banned from the server",
        Ban2: "for security reasons (You have exceeded the anti-raid sticker creation limit)",
        BanCatch1: "Member",
        BanCatch2: "Exceeded the Anti Raid limit but I can't ban him!",
    },
    stickerDelete: {
        removeRole1: "All your server roles",
        removeRole2: " have been removed for security reasons (You have exceeded the anti raid sticker removal limit)",
        removeRoleCatch1: "Member",
        removeRoleCatch2: "has exceeded the Anti Raid limit but I can't remove the role from it",
        Kick1: "You have been kicked fromdreamer",
        Kick2: "for security reasons (You have exceeded the anti raid sticker removal limit)",
        KickCatch1: "The Member",
        KickCatch2: "Exceeded the Anti Raid limit but I can't kick it!",
        Ban1: "You have been banned from the server",
        Ban2: "for security reasons (You have exceeded the anti-raid sticker removal limit)",
        BanCatch1: "Member",
        BanCatch2: "Exceeded the Anti Raid limit but I can't ban him!",
    },
    botAdd: {
        removeRole1: "All your server roles",
        removeRole2: " have been removed for security reasons (You cannot invite a bot)",
        removeRoleCatch1: "Member",
        removeRoleCatch2: "Added a bot and isn't whitelisted but I can't remove the role from it",
        Kick1: "You have been kicked from the server",
        Kick2: "for security reasons (You cannot invite a bot)",
        KickCatch1: "The Member",
        KickCatch2: " Added a bot and is not on the whitelist but I can't kick it!",
        Ban1: "You have been banned from the server",
        Ban2: "for security reasons (You cannot invite a bot)",
        BanCatch1: "Member",
        BanCatch2: " Added a bot and is not on the whitelist but I can't ban it!",
    },
    command: {
        notwhitelist: {
            title:"You must be on the whitelist!",
            description: "This command is reserved for people being subscribed to the whitelist!",
        },
        asset: {
            title: "You have just activated Emergency mode",
            description: "No more interactions can be executed in the server",
        },
        idle: {
            title: "You have just disabled Emergency mode",
            description: "All interactions can again be executed in the server",
        }
    },
    emergency: {
        removeRole1: "All your server roles",
        removeRole2: " have been removed for security reasons (Emergency mode is enabled)",
        removeRoleCatch1: "Member",
        removeRoleCatch2: "performed an action while not on the whitelist but I can't remove the role from him",
        Kick1: "You have been kicked from the server",
        Kick2: "for safety reasons (Emergency mode is activated)",
        KickCatch1: "The Member",
        KickCatch2: "performed an action when it's not on the whitelist but I can't kick it!",
        Ban1: "You have been banned from the server",
        Ban2: "for security reasons (Emergency mode is activated)",
        BanCatch1: "Member",
        BanCatch2: "performed an action while not on the whitelist but I can't ban him!",
    },
}