module.exports = {
    MissingToken: "Le token saisi est invalide ou introuvable !",
    InvalidIntent: "Vous devez sélectionner les intentions 'Guild_Members' dans votre discord developer portal !",
    error: "Une erreur inattendue est survenue ! Veuillez contacter le support pour obtenir de l'aide.",
    disable: "Désactivé",
    enable: "Activé",
    replace: "Remplacé",
    checkConfig: {
        DeveloperGuild: "Vous devez inscire l'indentifiant de votre serveur.",
        AntiRaid: "Les valeurs dans la config 'antiraid' doivent être égales à true / false",
        Urgence: "Les valeurs dans la config 'urgence' doivent être égales à true / false",
        limits: "Les valeurs dans la config 'limits' doivent être un nombre entier",
        restore: "Les valeurs dans la config 'restore' doivent être égales à true / false",
        sanction: "Les valeurs dans la config 'sanction' doivent être égales à 'Ban' / 'Kick' / 'RemoveRole'",
        warning1: "Attention ! dans votre config vous avez désactivé",
        warning2: "mais vous avez activé",
    },
    channelCreate: {
        removeRole1: "Tout vos rôles du serveur ",
        removeRole2: " ont été retiré pour des raisons de sécurité (Vous avez dépassé la limite de channels créés de l'anti raid)",
        removeRoleCatch1: "Le membre ",
        removeRoleCatch2: " à dépassé la limite de l'Anti Raid mais je ne peux pas lui retirer le rôle ",
        Kick1: "Vous avez été kick du serveur ",
        Kick2: " pour des raisons de sécurité (Vous avez dépassé la limite de channels créés de l'anti raid)",
        KickCatch1: "Le membre ",
        KickCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le kick !",
        Ban1: "Vous avez été banni du serveur ",
        Ban2: " pour des raisons de sécurité (Vous avez dépassé la limite de channels créés de l'anti raid)",
        BanCatch1: "Le membre ",
        BanCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le bannir !",
    },
    channelDelete: {
        removeRole1: "Tout vos rôles du serveur ",
        removeRole2: " ont été retiré pour des raisons de sécurité (Vous avez dépassé la limite de channels supprimés de l'anti raid)",
        removeRoleCatch1: "Le membre ",
        removeRoleCatch2: " à dépassé la limite de l'Anti Raid mais je ne peux pas lui retirer le rôle ",
        Kick1: "Vous avez été kick du serveur ",
        Kick2: " pour des raisons de sécurité (Vous avez dépassé la limite de channels supprimés de l'anti raid)",
        KickCatch1: "Le membre ",
        KickCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le kick !",
        Ban1: "Vous avez été banni du serveur ",
        Ban2: " pour des raisons de sécurité (Vous avez dépassé la limite de channels supprimés de l'anti raid)",
        BanCatch1: "Le membre ",
        BanCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le bannir !",
        embed: {
            title: "Anti raid - Channel recréé",
            description: "Ce channel a été supprimé par une personne malveillante, je l'ai donc recréé !",
        },
    },
    emojiCreate: {
        removeRole1: "Tout vos rôles du serveur ",
        removeRole2: " ont été retiré pour des raisons de sécurité (Vous avez dépassé la limite d'émojis créés de l'anti raid)",
        removeRoleCatch1: "Le membre ",
        removeRoleCatch2: " à dépassé la limite de l'Anti Raid mais je ne peux pas lui retirer le rôle ",
        Kick1: "Vous avez été kick du serveur ",
        Kick2: " pour des raisons de sécurité (Vous avez dépassé la limite d'émojis créés de l'anti raid)",
        KickCatch1: "Le membre ",
        KickCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le kick !",
        Ban1: "Vous avez été banni du serveur ",
        Ban2: " pour des raisons de sécurité (Vous avez dépassé la limite d'émojis créés de l'anti raid)",
        BanCatch1: "Le membre ",
        BanCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le bannir !",
    },
    emojiDelete: {
        removeRole1: "Tout vos rôles du serveur ",
        removeRole2: " ont été retiré pour des raisons de sécurité (Vous avez dépassé la limite d'émojis supprimés de l'anti raid)",
        removeRoleCatch1: "Le membre ",
        removeRoleCatch2: " à dépassé la limite de l'Anti Raid mais je ne peux pas lui retirer le rôle ",
        Kick1: "Vous avez été kick du serveur ",
        Kick2: " pour des raisons de sécurité (Vous avez dépassé la limite d'émojis supprimés de l'anti raid)",
        KickCatch1: "Le membre ",
        KickCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le kick !",
        Ban1: "Vous avez été banni du serveur ",
        Ban2: " pour des raisons de sécurité (Vous avez dépassé la limite d'émojis supprimés de l'anti raid)",
        BanCatch1: "Le membre ",
        BanCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le bannir !",
    },
    banAdd: {
        removeRole1: "Tout vos rôles du serveur ",
        removeRole2: " ont été retiré pour des raisons de sécurité (Vous avez dépassé la limite d'utilisateurs bannis de l'anti raid)",
        removeRoleCatch1: "Le membre ",
        removeRoleCatch2: " à dépassé la limite de l'Anti Raid mais je ne peux pas lui retirer le rôle ",
        Kick1: "Vous avez été kick du serveur ",
        Kick2: " pour des raisons de sécurité (Vous avez dépassé la limite d'utilisateurs bannis de l'anti raid)",
        KickCatch1: "Le membre ",
        KickCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le kick !",
        Ban1: "Vous avez été banni du serveur ",
        Ban2: " pour des raisons de sécurité (Vous avez dépassé la limite d'utilisateurs bannis de l'anti raid)",
        BanCatch1: "Le membre ",
        BanCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le bannir !",
    },
    banRemove: {
        removeRole1: "Tout vos rôles du serveur ",
        removeRole2: " ont été retiré pour des raisons de sécurité (Vous avez dépassé la limite d'utilisateurs débannis de l'anti raid)",
        removeRoleCatch1: "Le membre ",
        removeRoleCatch2: " à dépassé la limite de l'Anti Raid mais je ne peux pas lui retirer le rôle ",
        Kick1: "Vous avez été kick du serveur ",
        Kick2: " pour des raisons de sécurité (Vous avez dépassé la limite d'utilisateurs débannis de l'anti raid)",
        KickCatch1: "Le membre ",
        KickCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le kick !",
        Ban1: "Vous avez été banni du serveur ",
        Ban2: " pour des raisons de sécurité (Vous avez dépassé la limite d'utilisateurs débannis de l'anti raid)",
        BanCatch1: "Le membre ",
        BanCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le bannir !",
    },
    roleCreate: {
        removeRole1: "Tout vos rôles du serveur ",
        removeRole2: " ont été retiré pour des raisons de sécurité (Vous avez dépassé la limite de rôles créés de l'anti raid)",
        removeRoleCatch1: "Le membre ",
        removeRoleCatch2: " à dépassé la limite de l'Anti Raid mais je ne peux pas lui retirer le rôle ",
        Kick1: "Vous avez été kick du serveur ",
        Kick2: " pour des raisons de sécurité (Vous avez dépassé la limite de rôles créés de l'anti raid)",
        KickCatch1: "Le membre ",
        KickCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le kick !",
        Ban1: "Vous avez été banni du serveur ",
        Ban2: " pour des raisons de sécurité (Vous avez dépassé la limite de rôles créés de l'anti raid)",
        BanCatch1: "Le membre ",
        BanCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le bannir !",
    },
    roleDelete: {
        removeRole1: "Tout vos rôles du serveur ",
        removeRole2: " ont été retiré pour des raisons de sécurité (Vous avez dépassé la limite de rôles supprimées de l'anti raid)",
        removeRoleCatch1: "Le membre ",
        removeRoleCatch2: " à dépassé la limite de l'Anti Raid mais je ne peux pas lui retirer le rôle ",
        Kick1: "Vous avez été kick du serveur ",
        Kick2: " pour des raisons de sécurité (Vous avez dépassé la limite de rôles supprimées de l'anti raid)",
        KickCatch1: "Le membre ",
        KickCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le kick !",
        Ban1: "Vous avez été banni du serveur ",
        Ban2: " pour des raisons de sécurité (Vous avez dépassé la limite de rôles supprimées de l'anti raid)",
        BanCatch1: "Le membre ",
        BanCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le bannir !",
    },
    stickerCreate: {
        removeRole1: "Tout vos rôles du serveur ",
        removeRole2: " ont été retiré pour des raisons de sécurité (Vous avez dépassé la limite de création de stickers de l'anti raid)",
        removeRoleCatch1: "Le membre ",
        removeRoleCatch2: " à dépassé la limite de l'Anti Raid mais je ne peux pas lui retirer le rôle ",
        Kick1: "Vous avez été kick du serveur ",
        Kick2: " pour des raisons de sécurité (Vous avez dépassé la limite de création de stickers de l'anti raid)",
        KickCatch1: "Le membre ",
        KickCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le kick !",
        Ban1: "Vous avez été banni du serveur ",
        Ban2: " pour des raisons de sécurité (Vous avez dépassé la limite de création de stickers de l'anti raid)",
        BanCatch1: "Le membre ",
        BanCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le bannir !",
    },
    stickerDelete: {
        removeRole1: "Tout vos rôles du serveur ",
        removeRole2: " ont été retiré pour des raisons de sécurité (Vous avez dépassé la limite de suppression de stickers de l'anti raid)",
        removeRoleCatch1: "Le membre ",
        removeRoleCatch2: " à dépassé la limite de l'Anti Raid mais je ne peux pas lui retirer le rôle ",
        Kick1: "Vous avez été kick du serveur ",
        Kick2: " pour des raisons de sécurité (Vous avez dépassé la limite de suppression de stickersde l'anti raid)",
        KickCatch1: "Le membre ",
        KickCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le kick !",
        Ban1: "Vous avez été banni du serveur ",
        Ban2: " pour des raisons de sécurité (Vous avez dépassé la limite de suppression de stickers de l'anti raid)",
        BanCatch1: "Le membre ",
        BanCatch2: "  à dépassé la limite de l'Anti Raid mais je ne peux pas le bannir !",
    },
    botAdd: {
        removeRole1: "Tout vos rôles du serveur ",
        removeRole2: " ont été retiré pour des raisons de sécurité (Vous ne pouvez pas inviter de bot)",
        removeRoleCatch1: "Le membre ",
        removeRoleCatch2: " à Ajouté un bot et n'est pas sur la whitelist mais je ne peux pas lui retirer le rôle ",
        Kick1: "Vous avez été kick du serveur ",
        Kick2: " pour des raisons de sécurité (Vous ne pouvez pas inviter de bot)",
        KickCatch1: "Le membre ",
        KickCatch2: "  à Ajouté un bot et n'est pas sur la whitelist mais je ne peux pas le kick !",
        Ban1: "Vous avez été banni du serveur ",
        Ban2: " pour des raisons de sécurité (Vous ne pouvez pas inviter de bot)",
        BanCatch1: "Le membre ",
        BanCatch2: "  à Ajouté un bot et n'est pas sur la whitelist mais je ne peux pas le bannir !",
    },
    command: {
        notwhitelist: {
            title:"Vous devez être sur la whitelist !",
            description: "Cette commande est réservé aux personnes étant incrites à la whitelist !",
        },
        actif: {
            title: "Vous venez d'activer le mode Urgence",
            description: "Plus aucune interactions ne peut être éxécuter dans le serveur",
        },
        inactif: {
            title: "Vous venez de désactiver le mode Urgence",
            description: "Tout les interactions peuvent de nouveau être éxécuter dans le serveur",
        }
    },
    urgence: {
        removeRole1: "Tout vos rôles du serveur ",
        removeRole2: " ont été retiré pour des raisons de sécurité (Le mode urgence est activé)",
        removeRoleCatch1: "Le membre ",
        removeRoleCatch2: " à effectué une action alors qu'il n'est pas sur la whitelist mais je ne peux pas lui retirer le rôle ",
        Kick1: "Vous avez été kick du serveur ",
        Kick2: " pour des raisons de sécurité (Le mode urgence est activé)",
        KickCatch1: "Le membre ",
        KickCatch2: "  à effectué une action alors qu'il n'est pas sur la whitelist mais je ne peux pas le kick !",
        Ban1: "Vous avez été banni du serveur ",
        Ban2: " pour des raisons de sécurité (Le mode urgence est activé)",
        BanCatch1: "Le membre ",
        BanCatch2: "  à effectué une action alors qu'il n'est pas sur la whitelist mais je ne peux pas le bannir !",
    },
}