module.exports = {
    MissingToken: "",
    InvalidIntent: "",
    error: "",
    disable: "",
    enable: "",
    replace: "",
    checkConfig: {
        DeveloperGuild: "",
        AntiRaid: "",
        Urgence: "",
        limits: "",
        restore: "",
        sanction: "",
        warning1: "",
        warning2: "",
    },
    channelCreate: {
        removeRole1: " ",
        removeRole2: " ",
        removeRoleCatch1: " ",
        removeRoleCatch2: "  ",
        Kick1: " ",
        Kick2: " ",
        KickCatch1: " ",
        KickCatch2: " ",
        Ban1: " ",
        Ban2: " ",
        BanCatch1: " ",
        BanCatch2: " ",
    },
    channelDelete: {
        removeRole1: " ",
        removeRole2: " ",
        removeRoleCatch1: " ",
        removeRoleCatch2: "  ",
        Kick1: " ",
        Kick2: " ",
        KickCatch1: " ",
        KickCatch2: " ",
        Ban1: " ",
        Ban2: " ",
        BanCatch1: " ",
        BanCatch2: " ",
        embeds: {
            title: "",
            description: "",
        },
    },
    emojiCreate: {
        removeRole1: " ",
        removeRole2: " ",
        removeRoleCatch1: " ",
        removeRoleCatch2: "  ",
        Kick1: " ",
        Kick2: " ",
        KickCatch1: " ",
        KickCatch2: " ",
        Ban1: " ",
        Ban2: " ",
        BanCatch1: " ",
        BanCatch2: " ",
    },
    emojiDelete: {
        removeRole1: " ",
        removeRole2: " ",
        removeRoleCatch1: " ",
        removeRoleCatch2: "  ",
        Kick1: " ",
        Kick2: " ",
        KickCatch1: " ",
        KickCatch2: " ",
        Ban1: " ",
        Ban2: " ",
        BanCatch1: " ",
        BanCatch2: " ",
    },
    banAdd: {
        removeRole1: " ",
        removeRole2: " ",
        removeRoleCatch1: " ",
        removeRoleCatch2: "  ",
        Kick1: " ",
        Kick2: " ",
        KickCatch1: " ",
        KickCatch2: " ",
        Ban1: " ",
        Ban2: " ",
        BanCatch1: " ",
        BanCatch2: " ",
    },
    banRemove: {
        removeRole1: " ",
        removeRole2: " ",
        removeRoleCatch1: " ",
        removeRoleCatch2: "  ",
        Kick1: " ",
        Kick2: " ",
        KickCatch1: " ",
        KickCatch2: " ",
        Ban1: " ",
        Ban2: " ",
        BanCatch1: " ",
        BanCatch2: " ",
    },
    roleCreate: {
        removeRole1: " ",
        removeRole2: " ",
        removeRoleCatch1: " ",
        removeRoleCatch2: "  ",
        Kick1: " ",
        Kick2: " ",
        KickCatch1: " ",
        KickCatch2: " ",
        Ban1: " ",
        Ban2: " ",
        BanCatch1: " ",
        BanCatch2: " ",
    },
    roleDelete: {
        removeRole1: " ",
        removeRole2: " ",
        removeRoleCatch1: " ",
        removeRoleCatch2: "  ",
        Kick1: " ",
        Kick2: " ",
        KickCatch1: " ",
        KickCatch2: " ",
        Ban1: " ",
        Ban2: " ",
        BanCatch1: " ",
        BanCatch2: " ",
    },
    stickerCreate: {
        removeRole1: " ",
        removeRole2: " ",
        removeRoleCatch1: " ",
        removeRoleCatch2: "  ",
        Kick1: " ",
        Kick2: " ",
        KickCatch1: " ",
        KickCatch2: " ",
        Ban1: " ",
        Ban2: " ",
        BanCatch1: " ",
        BanCatch2: " ",
    },
    stickerDelete: {
        removeRole1: " ",
        removeRole2: " ",
        removeRoleCatch1: " ",
        removeRoleCatch2: "  ",
        Kick1: " ",
        Kick2: " ",
        KickCatch1: " ",
        KickCatch2: " ",
        Ban1: " ",
        Ban2: " ",
        BanCatch1: " ",
        BanCatch2: " ",
    },
    botAdd: {
        removeRole1: " ",
        removeRole2: " ",
        removeRoleCatch1: " ",
        removeRoleCatch2: "  ",
        Kick1: " ",
        Kick2: " ",
        KickCatch1: " ",
        KickCatch2: " ",
        Ban1: " ",
        Ban2: " ",
        BanCatch1: " ",
        BanCatch2: " ",
    },
    command: {
        notwhitelist: {
            title:"",
            description: "",
        },
        actif: {
            title: "",
            description: "",
        },
        inactif: {
            title: "",
            description: "",
        }
    },
    urgence: {
        removeRole1: " ",
        removeRole2: " ",
        removeRoleCatch1: " ",
        removeRoleCatch2: "  ",
        Kick1: " ",
        Kick2: " ",
        KickCatch1: " ",
        KickCatch2: "  ",
        Ban1: " ",
        Ban2: " ",
        BanCatch1: "",
        BanCatch2: " ",
    },
}